/**
 * 3pd run ai
 *
 * Launches Claude Code as an AI dev assistant inside the current app directory.
 * Generates CLAUDE.md from:
 *   - PROMPT.txt  (starter kit identity — static, committed)
 *   - .ai/LOG.md  (project memory — dynamic, committed)
 * Starts the dev server automatically (npm run dev) if not already running.
 * Kills the dev server when the Claude session ends.
 *
 * Supports React and Astro starter kits.
 * Framework is detected automatically from astro.config.mjs presence.
 *
 * CLAUDE.md is gitignored — session artifact, never committed.
 * .ai/LOG.md is committed — persists project memory across developers and sessions.
 */

import fs from 'fs';
import net from 'net';
import path from 'path';
import { execSync, spawn } from 'child_process';
import chalk from 'chalk';
import { log } from '../shared/log.js';

// Framework detection — check for astro.config.mjs in the app directory
function detectFramework(cwd) {
  if (fs.existsSync(path.join(cwd, 'astro.config.mjs'))) return 'astro';
  return 'react';
}

// Does this app have an Express backend?
function hasExpressServer(cwd) {
  return fs.existsSync(path.join(cwd, 'server', 'server.js'));
}

// Default ports by framework
const FRAMEWORK_DEFAULTS = {
  react: { devPort: 5173, serverPort: 4000 },
  astro: { devPort: 4321, serverPort: 3001 },
};

function readAppPorts(cwd, framework) {
  const defaults = FRAMEWORK_DEFAULTS[framework] || FRAMEWORK_DEFAULTS.react;
  const envPath = path.join(cwd, '.env');
  if (!fs.existsSync(envPath)) return { devPort: defaults.devPort, serverPort: defaults.serverPort };
  const env = fs.readFileSync(envPath, 'utf8');
  const dp = env.match(/^DEV_PORT=(\d+)/m);
  const sp = env.match(/^PORT=(\d+)/m);
  return {
    devPort:    dp ? parseInt(dp[1]) : defaults.devPort,
    serverPort: sp ? parseInt(sp[1]) : defaults.serverPort,
  };
}

// ------------------------------------------------------------
// Port utilities
// ------------------------------------------------------------
function isPortInUse(port) {
  // Check both IPv4 (127.0.0.1) and IPv6 (::1).
  // On macOS, Vite/Astro binds to 'localhost' which resolves to ::1 (IPv6).
  // Checking only 127.0.0.1 always returns false — causing a timeout.
  function checkHost(host) {
    return new Promise((resolve) => {
      const tester = net.createServer()
        .once('error', () => resolve(true))
        .once('listening', () => tester.close(() => resolve(false)))
        .listen(port, host);
    });
  }
  return Promise.all([checkHost('127.0.0.1'), checkHost('::1')])
    .then(([v4, v6]) => v4 || v6);
}

function waitForPort(port, timeoutMs = 15000) {
  return new Promise((resolve, reject) => {
    const start    = Date.now();
    const interval = setInterval(async () => {
      if (await isPortInUse(port)) {
        clearInterval(interval);
        resolve();
      } else if (Date.now() - start > timeoutMs) {
        clearInterval(interval);
        reject(new Error(`Timed out waiting for port ${port}`));
      }
    }, 300);
  });
}

async function isHttpReady(url, timeoutMs = 5000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    try {
      await fetch(url);
      return true;
    } catch {}
    await new Promise(r => setTimeout(r, 300));
  }
  return false;
}

// ------------------------------------------------------------
// Behavioral instructions block — baked into every CLAUDE.md
// ------------------------------------------------------------
const BEHAVIORAL_INSTRUCTIONS = `
## YOUR ROLE

You are the embedded AI development assistant for this project.
Behave like a senior engineer who knows this codebase intimately, tracks its progress,
and helps the developer move forward efficiently and confidently.

You have two sources of truth above:
  1. STARTER KIT IDENTITY (PROMPT.txt) — the architecture, conventions, and rules.
     Treat this as law. Do not suggest approaches that contradict it.
  2. PROJECT MEMORY (.ai/LOG.md) — the current status, roadmap, and session history.
     Read it carefully before responding. This is how you know where things stand.

## SESSION STARTUP — do this every time

1. Briefly confirm you have loaded the project context.
2. Give a 2–3 sentence summary of where the project stands based on the LOG.
3. Call out the top 2–3 next steps or open roadmap items.
4. If the dev server is running, mention the URL so the developer can open it alongside
   this conversation.
5. Ask what the developer wants to work on today — OR wait for them to paste a project
   brief (see DIRECTOR HANDOVER below).

Keep it short. The developer wants to get to work, not read a report.

## DIRECTOR HANDOVER

The developer may paste a project brief as their very first message. This brief was
generated by the 3PD Intake Director and contains everything gathered during intake:
their name, contact email, what they want to build, key features, data needs, constraints,
and a suggested first task.

When the developer's first message reads like a project brief (mentions their name/email,
describes a project goal, and includes a suggested first task):

1. Do NOT re-ask questions already answered in the brief.
2. Acknowledge the brief in 2–3 sentences: confirm who they are, restate their goal in
   your own words, and confirm the first task.
3. Update .ai/LOG.md immediately:
   - Current Status: populate from the brief (what they want to build, where they are starting)
   - Open Questions: note anything ambiguous or not covered in the brief
   - Roadmap: draft an initial roadmap based on the brief's goal and first task
4. Then get to work on the first task — do not ask for permission to start.

## DURING THE SESSION

- Follow the architecture and conventions in PROMPT.txt, especially the mandatory checklist.
- Enforce naming conventions: machine names, route namespacing, APP_SLUG pattern.
- When a question has a documented answer in PROMPT.txt, cite it rather than improvising.
- If unresolved questions come up, add them to the Open Questions section of .ai/LOG.md.
- When scaffolding code, follow the patterns already established in the starter kit.
- Never suggest libraries, patterns, or approaches not already in use unless the developer
  explicitly asks to evaluate alternatives.
- When discussing UI changes, refer the developer to the running app URL to verify visually.
- End every reply with the session footer defined in the SESSION FOOTER section below.
  Never omit it. Never modify it.

## SESSION WRAP-UP

When the developer types "Close Session" (the canonical close phrase):

1. Ask if there is anything else before closing out.
2. Run: git status --short
   Note any uncommitted changes in the Session History entry so the next developer
   knows what was left in-flight. Example: "Left with 3 modified files (src/pages/index.astro,
   server/routes/submissions.js, .ai/LOG.md) — run git status to review."
   If the working tree is clean, note that too.
3. Update .ai/LOG.md:
   - Add a dated entry to Session History describing what was accomplished,
     including the uncommitted files noted above.
   - Update Current Status to reflect where things stand now.
   - Update Roadmap: check off completed items, add new ones, reprioritize if needed.
   - Update Open Questions and Backlog if anything changed.
4. Confirm the LOG has been updated.
5. Remind the developer: if the dev server was started manually (not via 3pd run ai),
   run "3pd stop" to fully shut it down and free the ports.

Never skip the LOG update. It is how the next developer — or your next session —
picks up exactly where this one left off.
`.trim();

// ------------------------------------------------------------
// LOG template for new apps (first run only)
// ------------------------------------------------------------
function buildLogTemplate(appName, date, framework) {
  const isAstro    = framework === 'astro';
  const fwLine     = isAstro ? 'Astro + Express + SQLite' : 'React + Vite + Express + SQLite';
  const homePage   = isAstro ? 'src/pages/index.astro' : 'src/pages/Home.jsx';
  const moduleCmd  = isAstro ? '3pd astro module' : '3pd react module';
  const schemaLine = isAstro
    ? '2. [ ] Build out the UI in src/pages/index.astro'
    : '2. [ ] Build out the UI in src/pages/Home.jsx';

  return `# Project LOG — ${appName}

Framework: ${fwLine}
Created: ${date}

---

## Current Status

App scaffolded. First session not yet started.

---

## Roadmap

1. [ ] Define the app's purpose and data model
${schemaLine}
3. [ ] Customize Express routes in server/routes/submissions.js if needed
4. [ ] Run \`${moduleCmd}\` to package for Drupal

---

## Open Questions

- What is this app's purpose?
- What data does it need to store or display?
- Will the submissions table schema need customization?

---

## Backlog

(add lower-priority items here)

---

## Session History

(sessions will be logged here by your AI assistant)
`.trim();
}

// Kill the entire process group spawned by npm run dev
// (covers npm → concurrently → Vite/Astro + Express)
function killDevProcess(proc) {
  if (!proc || proc.exitCode !== null) return;
  try {
    process.kill(-proc.pid, 'SIGTERM');
  } catch {
    try { proc.kill(); } catch {}
  }
}

// ------------------------------------------------------------
// Main
// ------------------------------------------------------------
export default async function runAi({ ideRoot, validate = false }) {
  const cwd       = process.cwd();
  const framework = detectFramework(cwd);
  const hasServer = hasExpressServer(cwd);
  const { devPort, serverPort } = readAppPorts(cwd, framework);
  const DEV_PORT    = devPort;
  const SERVER_PORT = serverPort;

  const frameworkLabel = framework === 'astro' ? 'Astro' : 'React (Vite)';
  const moduleCommand  = framework === 'astro' ? '3pd astro module' : '3pd react module';

  // 1. Check claude CLI is installed
  try {
    execSync('which claude', { stdio: 'pipe' });
  } catch {
    log.error('Claude Code CLI not found.');
    console.log('');
    console.log('  Install it at:  https://claude.ai/code');
    console.log('  Then run:       3pd run ai');
    console.log('');
    process.exit(1);
  }

  // 2. Find PROMPT.txt
  //    Priority: local app PROMPT.txt → framework starter PROMPT.txt → React fallback
  const localPromptPath = path.join(cwd, 'PROMPT.txt');
  const starterPromptPaths = {
    astro:  path.join(ideRoot, 'apps', '0.starter-astro-forms', 'PROMPT.txt'),
    react:  path.join(ideRoot, 'apps', '0.starter-react',       'PROMPT.txt'),
  };
  const starterPromptPath = starterPromptPaths[framework] || starterPromptPaths.react;
  const promptPath = fs.existsSync(localPromptPath) ? localPromptPath : starterPromptPath;

  if (!fs.existsSync(promptPath)) {
    log.error('PROMPT.txt not found.');
    log.info('Run this command from inside an app directory (e.g. apps/astro---my-app).');
    process.exit(1);
  }

  const promptContent = fs.readFileSync(promptPath, 'utf8');

  // 3. Find or create .ai/LOG.md
  const aiDir  = path.join(cwd, '.ai');
  const logPath = path.join(aiDir, 'LOG.md');

  if (!fs.existsSync(aiDir)) fs.mkdirSync(aiDir, { recursive: true });

  let isFirstRun = false;

  if (!fs.existsSync(logPath)) {
    isFirstRun = true;
    const appName = path.basename(cwd);
    const date    = new Date().toISOString().split('T')[0];
    fs.writeFileSync(logPath, buildLogTemplate(appName, date, framework), 'utf8');
    console.log('');
    log.success('Created .ai/LOG.md — your project memory file.');
    log.info('Commit this file so the next developer picks up where you left off.');
    console.log('');
  }

  const logContent = fs.readFileSync(logPath, 'utf8');

  // 4. Start dev server if not already running
  let devProcess   = null;
  let devServerUrl = null;
  const alreadyRunning = await isPortInUse(DEV_PORT);

  if (alreadyRunning) {
    const httpOk = await isHttpReady(`http://localhost:${DEV_PORT}`, 2000);
    if (httpOk) {
      devServerUrl = `http://localhost:${DEV_PORT}`;
      log.info(`Dev server already running → ${devServerUrl}`);
    } else {
      log.warn(`Port ${DEV_PORT} is in use but not responding. Check your dev server.`);
    }
  } else {
    const hasPackageJson = fs.existsSync(path.join(cwd, 'package.json'));
    if (hasPackageJson) {
      console.log('');
      console.log('  ┌─────────────────────────────────────────────────────┐');
      console.log('  │  Starting your dev environment (npm run dev)        │');
      console.log('  │                                                     │');
      if (hasServer) {
        console.log('  │  This starts two servers:                           │');
        console.log(`  │    • ${frameworkLabel.padEnd(12)} → http://localhost:${DEV_PORT}         │`);
        console.log(`  │    • Express API    → http://127.0.0.1:${SERVER_PORT}         │`);
      } else {
        console.log('  │  This starts the dev server:                        │');
        console.log(`  │    • ${frameworkLabel.padEnd(12)} → http://localhost:${DEV_PORT}         │`);
      }
      console.log('  │                                                     │');
      console.log('  │  This may take a minute on first run.               │');
      console.log('  │  Your AI assistant will open automatically when     │');
      console.log('  │  the dev environment is ready.                      │');
      console.log('  └─────────────────────────────────────────────────────┘');
      console.log('');
      process.stdout.write('  Waiting for dev server');

      devProcess = spawn('npm', ['run', 'dev'], {
        cwd,
        stdio: 'ignore',
        detached: true,  // own process group — lets us kill Vite/Astro + Express together
      });
      devProcess.unref();

      devProcess.on('error', () => {
        console.log('');
        log.warn('Dev server failed to start. Run npm run dev manually.');
        devProcess = null;
      });

      try {
        const dotInterval = setInterval(() => process.stdout.write('.'), 600);
        await waitForPort(DEV_PORT, 20000);
        clearInterval(dotInterval);

        const httpOk = await isHttpReady(`http://localhost:${DEV_PORT}`);
        if (httpOk) {
          console.log(' ready');
          console.log('');
          devServerUrl = `http://localhost:${DEV_PORT}`;
          log.success(`App running at ${devServerUrl}`);
        } else {
          console.log(' failed');
          console.log('');
          log.warn('Dev server started but is not responding — it may have crashed.');
          log.info('Check for errors by running: npm run dev');
          log.info('Your AI session will still open. Start the server manually if needed.');
          if (devProcess) { killDevProcess(devProcess); devProcess = null; }
        }
      } catch {
        console.log('');
        log.warn('Dev server did not start within 20s. Run npm run dev manually.');
        if (devProcess) { killDevProcess(devProcess); devProcess = null; }
      }
    }
  }

  console.log('');

  // 5. Build CLAUDE.md
  const validateBlock = validate ? `
## VALIDATE ON CLOSE

The developer launched with --validate. When they type "Close Session":
1. Run \`3pd validate\` before updating the LOG.
2. Include a summary of the results (lint, security scan, a11y, tests) in the
   Session History entry. Note any failures the next developer should address.
3. Then proceed with the standard Close Session steps.
` : '';

  const devServerBlock = devServerUrl
    ? `\n## DEV SERVER\n\nThe app is running at **${devServerUrl}** (${frameworkLabel}).\n${hasServer ? `The API is running at **http://127.0.0.1:${SERVER_PORT}** (Express).\n` : ''}Reference these URLs when discussing UI or API changes.\n`
    : '';

  const isAstro = framework === 'astro';
  const firstRunScanFiles = isAstro ? [
    '- package.json (app name, dependencies)',
    '- src/pages/index.astro and other .astro pages (what UI and pages exist)',
    '- server/db/schema.sql (what data model is defined, if present)',
    '- server/routes/*.js (what API endpoints exist, if present)',
    '- README.md if present',
  ].join('\n     ') : [
    '- package.json (app name, dependencies)',
    '- src/App.jsx and src/pages/*.jsx (what UI and routes exist)',
    '- server/db/schema.sql (what data model is defined)',
    '- server/routes/*.js (what API endpoints exist)',
    '- README.md if present',
  ].join('\n     ');

  const firstRunNote = isFirstRun ? `
> **FIRST RUN — SCAN REQUIRED**
> No LOG history exists yet. Before presenting any summary or asking any questions:
>
> 1. Read these files to assess what has already been built:
>    ${firstRunScanFiles}
>
> 2. Make a judgment:
>    - If the app is a CLEAN SCAFFOLD (no custom code beyond the starter template default):
>      Introduce yourself briefly, explain how the dev workflow works, and invite them
>      to either paste a project brief (if they came from the 3PD Director) or describe
>      what they want to build. See DIRECTOR HANDOVER section below for how to handle a brief.
>    - If the app has REAL CODE beyond the template (custom UI, schema, routes, etc.):
>      Populate .ai/LOG.md with your observations before presenting anything:
>        - Current Status: what the app does, how far along it is
>        - Roadmap: what appears to still be needed based on the code
>        - Open Questions: anything ambiguous or undocumented in the code
>      Then present a 2–3 sentence summary of what you found and ask what to work on.
>
> Do not skip the scan. A wrong summary is worse than a slow start.
` : '';

  const appLine = devServerUrl
    ? `  ▎ App: ${devServerUrl}\n`
    : '';

  const sessionFooterBlock = `
## SESSION FOOTER

Append the following block verbatim at the end of every reply, without exception:

${appLine}  ▎ Type **Close Session** when you're done and I'll update the LOG with today's progress.
  ▎ Tip: Ask me to run \`3pd lint\`, \`3pd scan\`, \`3pd a11y\`, or \`3pd validate\` at any time.
  ▎ Tip: Ask me to run \`${moduleCommand}\` or \`${moduleCommand} --install\` when you're ready to turn this app into a Drupal Module.
  ▎ Tip: Run \`3pd stop\` after closing to fully shut down the dev server and free the ports.
`;

  const appName = path.basename(cwd);

  const claudeMd = `# ${appName} — AI Dev Assistant Context

<!-- Auto-generated by \`3pd run ai\`. Do not edit or commit. -->
<!-- Regenerated each session from PROMPT.txt + .ai/LOG.md.  -->
${firstRunNote}${validateBlock}${devServerBlock}
---

## STARTER KIT IDENTITY

The following is PROMPT.txt for this starter kit.
It defines the architecture, conventions, mandatory checklist, and known issues.
Treat it as law.

${promptContent}

---

## PROJECT MEMORY

The following is .ai/LOG.md — the persistent project history, roadmap, and session log.
Read it carefully before responding to the developer.

${logContent}

---

## BEHAVIORAL INSTRUCTIONS

${BEHAVIORAL_INSTRUCTIONS}
${sessionFooterBlock}`.trim();

  // 6. Write CLAUDE.md (session artifact — gitignored)
  const claudeMdPath = path.join(cwd, 'CLAUDE.md');
  fs.writeFileSync(claudeMdPath, claudeMd, 'utf8');

  // 7. Ensure CLAUDE.md is in .gitignore
  const gitignorePath = path.join(cwd, '.gitignore');
  if (fs.existsSync(gitignorePath)) {
    const gi = fs.readFileSync(gitignorePath, 'utf8');
    if (!gi.includes('CLAUDE.md')) {
      fs.appendFileSync(
        gitignorePath,
        '\n# AI assistant session context (auto-generated, never commit)\nCLAUDE.md\n'
      );
    }
  }

  // 8. Launch claude
  log.info('Starting AI dev assistant...');
  log.info(`Loaded: ${path.relative(cwd, promptPath)}  +  .ai/LOG.md`);
  console.log('');
  console.log(chalk.bgYellow.black.bold('  Type "Close Session" when done — Claude will update the LOG with today\'s progress.  '));
  console.log('');

  const child = spawn('claude', ['Begin session.'], { stdio: 'inherit', cwd });

  child.on('error', (err) => {
    if (devProcess) killDevProcess(devProcess);
    if (err.code === 'ENOENT') {
      log.error('claude command not found. Install Claude Code: https://claude.ai/code');
    } else {
      log.error(`Failed to start Claude: ${err.message}`);
    }
    process.exit(1);
  });

  child.on('exit', (code) => {
    if (devProcess) {
      killDevProcess(devProcess);
      console.log('');
      log.info('Dev server stopped. To restart: npm run dev');
    }
    process.exit(code ?? 0);
  });

  // Clean up dev server on unexpected termination
  process.on('SIGINT',  () => { if (devProcess) killDevProcess(devProcess); process.exit(0); });
  process.on('SIGTERM', () => { if (devProcess) killDevProcess(devProcess); process.exit(0); });
}
