/**
 * 3pd react app <name>
 * File: commands/react-app.js
 *
 * Copies /3pd-ide/apps/0.starter-react/starter-template → /3pd-ide/apps/react---<name>
 * then runs `npm install` inside the new folder.
 */

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { log } from '../shared/log.js';
import { FRAMEWORK_PREFIXES } from '../shared/frameworks.js';
import stylesSync from './styles-sync.js';

/**
 * Recursively copy a directory
 */
function copyRecursive(src, dest) {
  if (!fs.existsSync(src)) return;
  fs.mkdirSync(dest, { recursive: true });

  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    if (entry.name === 'node_modules') continue;
    if (entry.name === '.ai') continue; // generated by `3pd run ai` on first session

    const srcPath  = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);

    if (entry.isDirectory()) {
      copyRecursive(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

/**
 * Scan existing react apps for their assigned ports and return the next
 * available pair. Starts at 4000 (Express) / 5173 (Vite) and increments
 * by 1 for each additional app, so two apps get 4000/5173 + 4001/5174.
 */
function assignPorts(ideRoot) {
  const appsDir = path.join(ideRoot, 'apps');
  let maxExpress = 3999;
  let maxVite    = 5172;

  try {
    for (const entry of fs.readdirSync(appsDir, { withFileTypes: true })) {
      if (!entry.isDirectory() || !entry.name.startsWith('react---')) continue;
      const envPath = path.join(appsDir, entry.name, '.env');
      if (!fs.existsSync(envPath)) continue;
      const env = fs.readFileSync(envPath, 'utf8');
      const ep = env.match(/^PORT=(\d+)/m);
      const vp = env.match(/^DEV_PORT=(\d+)/m);
      if (ep) maxExpress = Math.max(maxExpress, parseInt(ep[1]));
      if (vp) maxVite    = Math.max(maxVite, parseInt(vp[1]));
      // Old apps without DEV_PORT implicitly use Vite's default (5173)
      else if (ep) maxVite = Math.max(maxVite, 5173);
    }
  } catch {}

  return { expressPort: maxExpress + 1, vitePort: maxVite + 1 };
}

function loadProjectConfig(appDir) {
  const configPath = path.join(appDir, '..', '..', '3pd.config.json');
  if (fs.existsSync(configPath)) {
    try { return JSON.parse(fs.readFileSync(configPath, 'utf8')); } catch {}
  }
  return {};
}

function setupEnvFile(appDir, folderName, config = {}, ports = {}) {
  const envExample = path.join(appDir, '.env.example');
  const envFile    = path.join(appDir, '.env');

  if (!fs.existsSync(envExample)) {
    log.warn('No .env.example found — skipping .env creation.');
    return;
  }

  const { expressPort = 4000, vitePort = 5173 } = ports;

  let envContent = fs.readFileSync(envExample, 'utf8');

  // Inject APP_SLUG from folder name
  envContent = envContent.replace(/APP_SLUG=YOUR_APP_SLUG/g, `APP_SLUG=${folderName}`);
  envContent = envContent.replace(/VITE_APP_SLUG=YOUR_APP_SLUG/g, `VITE_APP_SLUG=${folderName}`);

  // Inject assigned ports (unique per app so multiple apps can run simultaneously)
  envContent = envContent.replace(/^PORT=\d+/m,              `PORT=${expressPort}`);
  envContent = envContent.replace(/^DEV_PORT=\d+/m,          `DEV_PORT=${vitePort}`);
  envContent = envContent.replace(/^VITE_API_BASE_URL=.*/m,  `VITE_API_BASE_URL=http://127.0.0.1:${expressPort}`);
  envContent = envContent.replace(/^CORS_ORIGIN=.*/m,        `CORS_ORIGIN=http://localhost:${vitePort}`);

  // Inject Drupal base URL from project config (3pd.config.json) if available
  if (config.drupalBaseUrl) {
    envContent = envContent.replace(/^VITE_DRUPAL_BASE_URL=$/m, `VITE_DRUPAL_BASE_URL=${config.drupalBaseUrl}`);
  }

  fs.writeFileSync(envFile, envContent);
  log.success(`.env created — APP_SLUG: ${folderName}  |  ports: Express :${expressPort}  Vite :${vitePort}`);
}

/**
 * Main command handler
 * @param {string} name - App name from CLI
 * @param {{ ideRoot: string, internal: boolean }} opts
 */
export default async function reactApp(name, { ideRoot }) {
  log.header("Create New React App");

  if (!ideRoot) {
    log.error("Missing ideRoot. CLI did not pass correct options.");
    process.exit(1);
  }

  // Support multi-word names (Commander passes arrays when using <name...>)
  const rawName = Array.isArray(name) ? name.join(' ') : name;

  const slug = rawName
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-')          // spaces → hyphens
    .replace(/[^a-z0-9\-]/g, '');  // remove invalid chars

  if (!slug) {
    log.error("Invalid app name.");
    process.exit(1);
  }

  const folderName = FRAMEWORK_PREFIXES.react + slug;

  const templateDir = path.join(ideRoot, 'apps', '0.starter-react', 'starter-template');
  const appDir      = path.join(ideRoot, 'apps', folderName);

  if (!fs.existsSync(templateDir)) {
    log.error("Starter template not found.");
    log.dim(`Expected at: ${templateDir}`);
    log.nl();
    log.dim("Create /3pd-ide/apps/0.starter-react/starter-template first.");
    process.exit(1);
  }

  if (fs.existsSync(appDir)) {
    log.error("App already exists.");
    log.dim(appDir);
    process.exit(1);
  }

  // Display paths
  log.info(`App Name: ${folderName}`);
  log.dim(`Template: ${templateDir}`);
  log.dim(`Destination: ${appDir}`);
  log.nl();

  // Copy template
  log.header("Copying Starter Template");
  copyRecursive(templateDir, appDir);
  log.success("Template copied.");

  // Create .env from .env.example
  log.header("Configuring Environment");
  const config = loadProjectConfig(appDir);
  const ports  = assignPorts(ideRoot);
  setupEnvFile(appDir, folderName, config, ports);

  // Patch package.json name
  const pkgPath = path.join(appDir, 'package.json');
  if (fs.existsSync(pkgPath)) {
    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    pkg.name = folderName;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
    log.success(`package.json updated → "${folderName}"`);
  }

  // Install dependencies
  log.header("Installing Dependencies");
  try {
    execSync('npm install', { cwd: appDir, stdio: 'inherit' });
  } catch (err) {
    log.error("npm install failed.");
    log.debug(err);
    process.exit(1);
  }

  // Sync Drupal dev assets (CSS + JS) into the new app's public/ folder
  log.header("Syncing Drupal Dev Assets");
  await stylesSync({ ideRoot });

  // Final summary
  log.header("Summary");
  log.success(`React app "${folderName}" created successfully.`);
  if (config.drupalBaseUrl) {
    log.success(`Drupal base URL set → ${config.drupalBaseUrl}`);
  } else {
    log.warn('VITE_DRUPAL_BASE_URL not set — add drupalBaseUrl to 3pd.config.json to enable Drupal content fetching.');
  }
  log.dim('Next steps:');
  log.dim(`  cd apps/${folderName}`);
  log.dim('');
  log.dim('  With AI assistant (recommended):');
  log.dim('  3pd run ai           # starts dev server + opens AI session');
  log.dim('  Requires: Claude Code CLI (any terminal or IDE) — https://claude.ai/code');
  log.dim('');
  log.dim('  Without AI:');
  log.dim('  npm run dev          # starts React (Vite) + Express together');
  log.dim('');
  log.dim('  When ready to ship:');
  log.dim('  3pd react module     # generates the Drupal block module');
  log.nl();
}
