<?php

namespace Drupal\hudx_astro_forms___temp_astro_form_page\Controller;

use Drupal\Core\Controller\ControllerBase;
use Drupal\Core\Menu\MenuTreeParameters;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Returns Drupal menu items as JSON.
 *
 * GET /api/astro-forms---temp-astro-form-page/menu/{menu_name}
 *
 * Generated by 3PD module generator — do not edit manually.
 */
class MenuController extends ControllerBase {

  public function items(Request $request, string $menu_name): JsonResponse {
    $menu_tree  = \Drupal::service('menu.link_tree');
    $parameters = new MenuTreeParameters();
    $parameters->setMinDepth(1)->setMaxDepth(2)->onlyEnabledLinks();
    $tree = $menu_tree->load($menu_name, $parameters);

    $manipulators = [
      ['callable' => 'menu.default_tree_manipulators:checkAccess'],
      ['callable' => 'menu.default_tree_manipulators:generateIndexAndSort'],
    ];
    $tree = $menu_tree->transform($tree, $manipulators);

    $items = [];
    foreach ($tree as $element) {
      $link     = $element->link;
      $url_obj  = $link->getUrlObject();
      $children = [];

      if (!empty($element->subtree)) {
        $child_manipulators = $manipulators;
        $subtree = $menu_tree->transform($element->subtree, $child_manipulators);
        foreach ($subtree as $child_element) {
          $child_link    = $child_element->link;
          $child_url_obj = $child_link->getUrlObject();
          $children[]    = [
            'title'  => $child_link->getTitle(),
            'url'    => $child_url_obj->setAbsolute(FALSE)->toString(),
            'weight' => $child_link->getWeight(),
          ];
        }
      }

      $items[] = [
        'title'    => $link->getTitle(),
        'url'      => $url_obj->setAbsolute(FALSE)->toString(),
        'weight'   => $link->getWeight(),
        'children' => $children,
      ];
    }

    $response = new JsonResponse($items);
    $response->headers->set('Cache-Control', 'no-store');
    return $response;
  }

}
