<?php

namespace Drupal\hudx_astro_forms___temp_astro_form_page\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\Response;

/**
 * Serves the 3PD IDE - Astro Forms   Temp Astro Form Page Astro app at /astro-forms---temp-astro-form-page.
 *
 * Returns a raw Symfony Response with the pre-built Astro HTML (dist/page.html),
 * bypassing Drupal's theming layer entirely so no site header/footer/nav appears.
 *
 * Generated by 3PD module generator — do not edit manually.
 */
class PageController extends ControllerBase {

  public function page(): Response {
    $module_path = \Drupal::service('extension.list.module')->getPath('hudx_astro_forms___temp_astro_form_page');
    $html_file   = \Drupal::root() . '/' . $module_path . '/dist/page.html';
    $html        = file_exists($html_file) ? file_get_contents($html_file) : '<p>App not built.</p>';
    if (\Drupal::currentUser()->isAuthenticated()) {
      $html = str_replace('<body', '<body data-drupal-auth="1"', $html);
    }
    return new Response($html, 200, ['Content-Type' => 'text/html; charset=utf-8']);
  }

  public function subpage_page2(): Response {
    $module_path = \Drupal::service('extension.list.module')->getPath('hudx_astro_forms___temp_astro_form_page');
    $html_file   = \Drupal::root() . '/' . $module_path . '/dist/page2.html';
    $html        = file_exists($html_file) ? file_get_contents($html_file) : '<p>Page not built.</p>';
    if (\Drupal::currentUser()->isAuthenticated()) {
      $html = str_replace('<body', '<body data-drupal-auth="1"', $html);
    }
    return new Response($html, 200, ['Content-Type' => 'text/html; charset=utf-8']);
  }
}
