<?php

namespace Drupal\hudx_astro_forms___3pd_checklist\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * Checklist API controller for 3PD Module Checklist.
 *
 * GET  /api/astro-forms---3pd-checklist/modules   — list installed hudx_* modules with tech type.
 * GET  /api/astro-forms---3pd-checklist/checklist — return all checklist rows.
 * POST /api/astro-forms---3pd-checklist/checklist — upsert a row by module_name.
 *
 * Mirrors the local Express server for production use.
 * Generated by 3PD module generator — do not edit manually.
 */
class ChecklistController extends ControllerBase {

  /**
   * Returns all installed hudx_* modules with parsed tech type and display name.
   *
   * Drupal machine names follow the pattern: hudx_{framework}___{slug}
   * e.g. hudx_react___3pd_depot → module_name: "react---3pd-depot", tech_type: "React"
   * All underscores become hyphens to recover the original folder name.
   */
  public function modules(): JsonResponse {
    $installed = \Drupal::service('extension.list.module')->getAllInstalledInfo();

    $tech_prefixes = [
      'hudx_astro_forms___' => 'Astro Forms',
      'hudx_react___'       => 'React',
      'hudx_astro___'       => 'Astro',
    ];

    $result = [];
    foreach ($installed as $machine => $info) {
      if ($machine === 'hudx_astro_forms___3pd_checklist') continue; // skip self

      foreach ($tech_prefixes as $prefix => $tech_type) {
        if (strpos($machine, $prefix) === 0) {
          // Recover folder name: strip 'hudx_', replace all _ with -
          $app_name     = str_replace('_', '-', substr($machine, 5));
          $slug_prefix  = strtolower(str_replace(' ', '-', $tech_type)) . '---';
          $display_name = substr($app_name, strlen($slug_prefix));

          $result[] = [
            'module_name'  => $app_name,
            'tech_type'    => $tech_type,
            'display_name' => $display_name,
          ];
          break;
        }
      }
    }

    return new JsonResponse($result);
  }

  /**
   * Returns all checklist rows, ordered by id.
   */
  public function list(): JsonResponse {
    $rows = \Drupal::database()
      ->select('hudx_astro_forms___3pd_checklist_checklist', 'c')
      ->fields('c')
      ->orderBy('c.id', 'ASC')
      ->execute()
      ->fetchAll(\PDO::FETCH_ASSOC);

    return new JsonResponse(array_values($rows));
  }

  /**
   * Upserts a checklist row by module_name.
   * Creates the row if it does not exist, updates it if it does.
   */
  public function upsert(Request $request): JsonResponse {
    $data = json_decode($request->getContent(), TRUE);

    if (empty($data['module_name'])) {
      return new JsonResponse(['error' => 'module_name is required.'], 400);
    }

    $db          = \Drupal::database();
    $module_name = $data['module_name'];
    $checked     = !empty($data['checked']) ? 1 : 0;
    $tester_name = $data['tester_name'] ?? '';
    $checked_at  = ($checked && $tester_name) ? date('Y-m-d H:i:s') : '';

    $existing = $db->select('hudx_astro_forms___3pd_checklist_checklist', 'c')
      ->fields('c', ['id'])
      ->condition('module_name', $module_name)
      ->execute()
      ->fetchField();

    if ($existing) {
      $db->update('hudx_astro_forms___3pd_checklist_checklist')
        ->fields([
          'tech_type'    => $data['tech_type']    ?? '',
          'display_name' => $data['display_name'] ?? '',
          'checked'      => $checked,
          'tester_name'  => $tester_name,
          'checked_at'   => $checked_at,
        ])
        ->condition('module_name', $module_name)
        ->execute();
    }
    else {
      $db->insert('hudx_astro_forms___3pd_checklist_checklist')
        ->fields([
          'module_name'  => $module_name,
          'tech_type'    => $data['tech_type']    ?? '',
          'display_name' => $data['display_name'] ?? '',
          'checked'      => $checked,
          'tester_name'  => $tester_name,
          'checked_at'   => $checked_at,
        ])
        ->execute();
    }

    $row = $db->select('hudx_astro_forms___3pd_checklist_checklist', 'c')
      ->fields('c')
      ->condition('module_name', $module_name)
      ->execute()
      ->fetchAssoc();

    return new JsonResponse($row);
  }

}
