<?php

namespace Drupal\hudx_astro_forms___app_12\Controller;

use Drupal\Core\Controller\ControllerBase;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;

/**
 * REST-like API for form submissions — mirrors the local Express server.
 *
 * GET  /api/submissions  — returns all rows, newest first.
 * POST /api/submissions  — inserts a new row.
 *
 * Generated by 3PD module generator — do not edit manually.
 */
class SubmissionsController extends ControllerBase {

  public function list(): JsonResponse {
    $rows = \Drupal::database()
      ->select('hudx_astro_forms___app_12_submissions', 's')
      ->fields('s')
      ->orderBy('s.id', 'DESC')
      ->execute()
      ->fetchAll(\PDO::FETCH_ASSOC);

    return new JsonResponse(array_values($rows));
  }

  public function submit(Request $request): JsonResponse {
    $data = json_decode($request->getContent(), TRUE);

    if (empty($data['name']) || empty($data['message'])) {
      return new JsonResponse(['error' => 'name and message are required.'], 400);
    }

    \Drupal::database()
      ->insert('hudx_astro_forms___app_12_submissions')
      ->fields([
        'name'       => $data['name'],
        'message'    => $data['message'],
        'created_at' => date('Y-m-d H:i:s'),
      ])
      ->execute();

    return new JsonResponse(['status' => 'ok'], 201);
  }

}
