/**
 * HUDX Smart Embed — parent-side resize listener.
 * Listens for hudx-resize postMessage from the embedded iframe child
 * and updates the iframe height accordingly.
 *
 * Generated by 3PD module generator. Do not edit manually.
 */
(function (Drupal, once) {
  'use strict';

  Drupal.behaviors.hudxSmartEmbed = {
    attach(context) {
      once('hudx-smart-embed', '.hudx-smart-embed', context).forEach(function (wrapper) {
        var iframe = wrapper.querySelector('iframe');
        if (!iframe) return;

        // Apply fallback height until the child sends its real height
        iframe.style.height = '600px';

        window.addEventListener('message', function (e) {
          if (
            e.data &&
            e.data.type === 'hudx-resize' &&
            typeof e.data.height === 'number' &&
            e.data.height > 0
          ) {
            iframe.style.height = e.data.height + 'px';
          }
        });
      });
    },
  };
})(Drupal, once);
