<?php

/**
 * Implements hook_theme().
 *
 * IMPORTANT:
 * - $path refers to the active theme, NOT the module.
 * - Always use moduleHandler()->getModule()->getPath() for module templates.
 */
function hudx_decouple_app_test_theme($existing, $type, $theme, $path) {
  return [
    'hudx_decouple_app_test_block' => [
      'variables' => [],
      'template' => 'decouple-app-test-block',
      'path' => \Drupal::moduleHandler()
        ->getModule('hudx_decouple_app_test')
        ->getPath() . '/templates',
    ],
  ];
}
